const translations = {
    es: {
      nav_inicio: "Inicio",
      nav_nosotros: "Nosotros",
      nav_sedes: "Sedes",
      nav_dentistas: "Dentistas",
      nav_tratamientos: "Nuestros Tratamientos",
      nav_servicios: "Servicios",
      nav_cotice: "Cotice su procedimiento",
      nav_modelo3d: "Modelo 3D",
      nav_encuesta: "Encuesta",
      nav_galeria: "Galería",
      nav_procedimientos: "Procedimientos",
      nav_contacto: "Contacto",
      nav_formulario: "Formulario",
      nav_inscripcion: "Inscripción",
      nav_agendar: "Agendar Cita",
      hero_bienvenidos: "Bienvenidos a Dentisalud",
      hero_ofrecemos: "Ofrecemos una amplia gama de servicios dentales para garantizar tu salud bucal. Contamos con un equipo de profesionales altamente capacitados.",
      tratamientos_titulo: "Opciones de Tratamientos",
      odontologia_preventiva: "Odontología Preventiva",
      odontologia_preventiva_desc: "La prevención es la base de una buena salud bucal. Al priorizar los controles y limpiezas dentales regulares, puede evitar complicaciones costosas, como caries y enfermedades de las encías.",
      odontologia_restauradora: "Odontología Restauradora",
      odontologia_restauradora_desc: "La vida puede pasar factura a sus dientes, pero procedimientos como empastes o implantes dentales ayudan a restaurar no solo su salud bucal sino también su confianza.",
      emergencias_dentales: "Emergencias Dentales",
      emergencias_dentales_desc: "Las emergencias dentales son estresantes, pero Dentisalud está aquí para brindarle atención rápida y compasiva cuando más la necesita.",
      invisalign: "Invisalign",
      invisalign_desc: "Con Invisalign, obtienes un tratamiento prácticamente invisible para que puedas mantener una sonrisa de apariencia natural mientras logras la alineación perfecta que has estado buscando.",
      cosmetica_dental: "Cosmética Dental",
      cosmetica_dental_desc: "La sonrisa de tus sueños está a solo una consulta de distancia. Nuestros servicios de odontología cosmética están diseñados para realzar la belleza natural de su sonrisa y aumentar su confianza en sí mismo.",
      blanqueamiento: "Blanqueamiento",
      blanqueamiento_desc: "Lograr esa sonrisa de Hollywood nunca ha sido tan fácil. Ofrecemos dos opciones de blanqueamiento dental, ambas realizadas en una sola cita y adaptadas a sus preferencias de brillo.",
      mas_info: "Más Información",
      ayudandote_sonrisa: "Ayudándote a lograr la sonrisa de tus sueños",
      objetivo: "Nuestro objetivo como dentistas familiares es establecer conexiones de por vida con nuestros pacientes. Nos esforzamos por crear sonrisas saludables y cambiar su forma de pensar acerca de ver al dentista. En nuestra práctica dental, nos dedicamos a prevenir, diagnosticar y tratar problemas de salud bucal. Priorizamos su comodidad, utilizamos la tecnología dental más nueva y brindamos una atención transparente al paciente. En Dentisalud, recibirá servicios dentales integrales y sin prejuicios que son excepcionales y asequibles.",
      instalaciones: "Nuestras Instalaciones",
      testimonios_titulo: "Testimonios de pacientes",
      testimonio1: "Gracias a Dentisalud ahora puedo sonreír tranquila, su servicio es increíble.",
      testimonio2: "El Dr. Aguirre es muy profesional y atento, gracias a Dentisalud por su atención.",
      testimonio3: "Antes me daba miedo ir al dentista, desde que conocí Dentisalud mi vida cambió.",
      testimonio4: "Muy satisfecho con la clínica Dentisalud, muchas gracias!",
      testimonio5: "Atienden bien, saben escuchar las sugerencias de los pacientes, son muy profesionales.",
      sonrisa_tarjeta: "Tu sonrisa es nuestra mejor tarjeta de presentación",
      nuestros_dentistas: "Nuestros Dentistas",
      contactenos: "Contáctenos",
      nombre: "Nombre",
      apellido: "Apellido",
      correo: "Correo",
      telefono: "Teléfono",
      mensaje: "Mensaje",
      enviar: "Enviar",
      suscribete: "Suscríbete para obtener nuestro boletín mensual con noticias, información y descuentos",
      tu_email: "Tu email",
      pacientes_satisfechos: "Pacientes satisfechos en Dentisalud",
      limpiezas_2024: "Limpiezas dentales en 2024",
      sonrisas_invisalign: "Sonrisas perfectas con Invisalign",
      sonrisas_felices: "Sonrisas felices",
      clientes_satisfechos: "Clientes satisfechos",
      todos_derechos: "© 2024 Todos los derechos reservados | Dentisalud"
    },
    en: {
      nav_inicio: "Home",
      nav_nosotros: "About Us",
      nav_sedes: "Locations",
      nav_dentistas: "Dentists",
      nav_tratamientos: "Our Treatments",
      nav_servicios: "Services",
      nav_cotice: "Get a Quote",
      nav_modelo3d: "3D Model",
      nav_encuesta: "Survey",
      nav_galeria: "Gallery",
      nav_procedimientos: "Procedures",
      nav_contacto: "Contact",
      nav_formulario: "Form",
      nav_inscripcion: "Sign Up",
      nav_agendar: "Schedule Appointment",
      hero_bienvenidos: "Welcome to Dentisalud",
      hero_ofrecemos: "We offer a wide range of dental services to ensure your oral health. Our team of highly skilled professionals is ready to assist you.",
      tratamientos_titulo: "Treatment Options",
      odontologia_preventiva: "Preventive Dentistry",
      odontologia_preventiva_desc: "Prevention is the cornerstone of good oral health. By prioritizing regular check-ups and cleanings, you can avoid costly complications such as cavities and gum disease.",
      odontologia_restauradora: "Restorative Dentistry",
      odontologia_restauradora_desc: "Life can take a toll on your teeth, but procedures like fillings or dental implants help restore not only your oral health but also your confidence.",
      emergencias_dentales: "Dental Emergencies",
      emergencias_dentales_desc: "Dental emergencies are stressful, but Dentisalud is here to provide you with prompt and compassionate care when you need it most.",
      invisalign: "Invisalign",
      invisalign_desc: "With Invisalign, you get a virtually invisible treatment so you can maintain a natural-looking smile while achieving the perfect alignment you've been seeking.",
      cosmetica_dental: "Cosmetic Dentistry",
      cosmetica_dental_desc: "The smile of your dreams is just a consultation away. Our cosmetic dentistry services are designed to enhance the natural beauty of your smile and boost your confidence.",
      blanqueamiento: "Whitening",
      blanqueamiento_desc: "Achieving that Hollywood smile has never been easier. We offer two whitening options, both completed in a single visit and tailored to your preferred level of brightness.",
      mas_info: "More Information",
      ayudandote_sonrisa: "Helping You Achieve the Smile of Your Dreams",
      objetivo: "Our goal as family dentists is to establish lifelong connections with our patients. We strive to create healthy smiles and change your perspective about visiting the dentist. In our dental practice, we are dedicated to preventing, diagnosing, and treating oral health problems. We prioritize your comfort, use the latest dental technology, and provide transparent patient care. At Dentisalud, you will receive comprehensive and non-judgmental dental services that are exceptional and affordable.",
      instalaciones: "Our Facilities",
      testimonios_titulo: "Patient Testimonials",
      testimonio1: "Thanks to Dentisalud I can now smile peacefully, their service is incredible.",
      testimonio2: "Dr. Aguirre is very professional and attentive, thank you Dentisalud for your care.",
      testimonio3: "I used to be afraid of going to the dentist, since I met Dentisalud my life has changed.",
      testimonio4: "Very satisfied with the Dentisalud clinic, thank you very much!",
      testimonio5: "They attend well, they know how to listen to patients' suggestions, they are very professional.",
      sonrisa_tarjeta: "Your smile is our best business card",
      nuestros_dentistas: "Our Dentists",
      contactenos: "Contact Us",
      nombre: "Name",
      apellido: "Last Name",
      correo: "Email",
      telefono: "Phone",
      mensaje: "Message",
      enviar: "Send",
      suscribete: "Subscribe to receive our monthly newsletter with news, information, and discounts",
      tu_email: "Your email",
      pacientes_satisfechos: "Satisfied Patients at Dentisalud",
      limpiezas_2024: "Dental Cleanings in 2024",
      sonrisas_invisalign: "Perfect Smiles with Invisalign",
      sonrisas_felices: "Happy Smiles",
      clientes_satisfechos: "Satisfied Clients",
      todos_derechos: "© 2024 All rights reserved | Dentisalud"
    }
  };
  
  // función para cambiar el idioma
  function changeLanguage() {
      const lang = document.documentElement.lang === 'es' ? 'en' : 'es';
      document.documentElement.lang = lang;
  
      // cambiar texto de los elementos con data-translate
      document.querySelectorAll('[data-translate]').forEach(element => {
          const key = element.getAttribute('data-translate');
          element.innerHTML = translations[lang][key];
      });
  }
  